### ISSUE TITLE
Test validatesHtmlDocument() in DefaultHtmlValidatorTest is incorrect

### ISSUE THREAD

**Issue by prondzyn** [jcabi/jcabi-w3c#16]
I just was making some tests and I discovered that test [DefaultHtmlValidatorTest.validatesHtmlDocument()](https://github.com/jcabi/jcabi-w3c/blob/master/src/test/java/com/jcabi/w3c/DefaultHtmlValidatorTest.java#L50-L71) does not work correctly. 

When I changed [line 68](https://github.com/jcabi/jcabi-w3c/blob/master/src/test/java/com/jcabi/w3c/DefaultHtmlValidatorTest.java#L68) to
```java
final ValidationResponse response = validator.validate("this is invalid html");
```
the test still passes without problem even though "this is invalid html" is not a correct HTML.

**Comment by dmarkov** [comment]
@yegor256 please pay attention to this issue ([par.21](http://at.teamed.io/policy.html#21))

**Comment by dmarkov** [comment]
@prondzyn thank you for the ticket reported, I topped your account for 15 mins, transaction `AP-06L02252VD0346059`

**Comment by dmarkov** [comment]
@jrdalpra please pick this up, and keep in mind [these instructions](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions - ask right here

The budget of this task is **30 mins**. This is exactly how much time will be compensated, when the task is completed. Read about our [Definition of Done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by jrdalpra** [comment]
@dmarkov I'm not sure that it's a bug. I think that we need to make a new test to validade if the W3C response for an invalid html has the validity tag with false value and has a list of errors attached. The first test is correct to me. 

Other thing to do is implement a integration test to validade the same invalid html string.

Am I wrong?

**Comment by dmarkov** [comment]
> @dmarkov I'm not sure that it's a bug. I think that we need to make a new test to validade if the W3C response for an invalid html has the validity tag with false value and has a list of errors attached. The first test is correct to me. 
> 
> Other thing to do is implement a integration test to validade the same invalid html string.
> 
> Am I wrong?
> 

@jrdalpra you should discuss that with the ticket author, not with me, see http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html

**Comment by jrdalpra** [comment]
@dmarkov @yegor256 @prondzyn Can we close this issue?

**Comment by jrdalpra** [comment]
@dmarkov @yegor256 @dmzaytsev PR merged and task still open at netbout. How can we solve it?

**Comment by dmarkov** [comment]
> @dmarkov @yegor256 @prondzyn Can we close this issue?

@jrdalpra you should ask ticket author to close it, see http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html

**Comment by jrdalpra** [comment]
@prondzyn Close this ticket, please! Thanks.

**Comment by jrdalpra** [comment]
@dmarkov I already asked ... you can see above!

**Comment by jrdalpra** [comment]
@prondzyn, please close the ticket if you don't have any further questions.

**Comment by jrdalpra** [comment]
@dmarkov closed. 
@prondzyn thanks.

**Comment by dmarkov** [comment]
> @dmarkov @yegor256 @dmzaytsev PR merged and task still open at netbout. How can we solve it?

@jrdalpra did you remove the puzzle from the source code?

**Comment by dmarkov** [comment]
> @dmarkov closed. 
> @prondzyn thanks.

@jrdalpra sure, no problem

**Comment by dmarkov** [comment]
@jrdalpra I added **30 mins** to your account, many thanks for working with the project! The completion time here was AP-70W32907W0806124F.... +30 added to your rating, current score is: [+30](http://www.netbout.com/b/36044?open=rating)

**Comment by jrdalpra** [comment]
@dmarkov thanks for your patience. Next tasks will be more easily solved. 

Waiting  you to close the jcabi-dynamo task.

**Comment by dmarkov** [comment]
> @dmarkov thanks for your patience. Next tasks will be more easily solved. 
> 
> Waiting  you to close the jcabi-dynamo task.

@jrdalpra OK
