### ISSUE TITLE
DefaultHtmlValidatorTest.java:83-86: DefaultHtmlValidator have to be updated...

### ISSUE THREAD

**Issue by dmarkov** [jcabi/jcabi-w3c#19]
Puzzle `10-80fda63a` in `src/test/java/com/jcabi/w3c/DefaultHtmlValidatorTest.java:83-86` has to be resolved: DefaultHtmlValidator have to be updated to throw only IOException when W3C validation server is unavailable. Any other exception type can be confusing for users. Remove @Ignore annotation after finishing implementation.... The puzzle was created by Piotr Pradzynski on 6-Nov-2015.

If you have any technical questions, don't ask me, submit new tickets instead

**Comment by dmarkov** [comment]
@piddubnyi please go ahead, it's your task now, keep [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions you may have

Budget here is **30 mins** (keep [this principle](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind)

**Comment by dmarkov** [comment]
@piddubnyi the ticket is with you for 15 days already. If it is not finished in the next 48 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle, [this article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck. as a reminder, don't forget to remove the `@todo` puzzle from the source code. added -30 to your rating, now it is equal to [-60](http://www.netbout.com/b/35966?open=rating)

**Comment by piddubnyi** [comment]
@dmarkov PR https://github.com/jcabi/jcabi-w3c/pull/26 is already merged, please close this ticket.

**Comment by dmarkov** [comment]
@yegor256 Closing this issue now...

**Comment by dmarkov** [comment]
@piddubnyi Many thanks! **30 mins** were added to your account in Transaction ID `73087774` (task took 364 hours and 3 mins); added +30 to your rating, now it is equal to [-60](http://www.netbout.com/b/35966?open=rating)
