### ISSUE TITLE
DefaultCssValidatorTest.java:95-98: DefaultCssValidator have to be updated...

### ISSUE THREAD

**Issue by dmarkov** [jcabi/jcabi-w3c#20]
Puzzle `10-1838eb03` in `src/test/java/com/jcabi/w3c/DefaultCssValidatorTest.java:95-98` has to be resolved: DefaultCssValidator have to be updated to throw only IOException when W3C validation server is unavailable. Any other exception type can be confusing for users. Remove @Ignore annotation after finishing implementation.... The puzzle was created by Piotr Pradzynski on 7-Dec-2015.

If you have any technical questions, don't ask me, submit new tickets instead

<hr id='w'>

**Comment by dmarkov** [comment]
@jrdalpra please proceed, it's yours

**Comment by jrdalpra** [comment]
@dmarkov PR https://github.com/jcabi/jcabi-w3c/pull/30 waiting for someone to review. Thanks.

**Comment by dmarkov** [comment]
> @dmarkov PR https://github.com/jcabi/jcabi-w3c/pull/30 waiting for someone to review. Thanks.

@jrdalpra sure, no problem

**Comment by jrdalpra** [comment]
@dmarkov the PR #30 is blocked by this issue https://github.com/yegor256/rultor/issues/976. What can we do about it? Thanks.

**Comment by jrdalpra** [comment]
@dmarkov What should I do? There's an impediment blocking me. Thanks.

**Comment by jrdalpra** [comment]
@dmarkov PR #30 is merged. Can you close this issue? Thanks.

**Comment by dmarkov** [comment]
> @dmarkov the PR #30 is blocked by this issue https://github.com/yegor256/rultor/issues/976. What can we do about it? Thanks.

@jrdalpra just wait a bit, we will find a reviewer soon

**Comment by jrdalpra** [comment]
@dmarkov it was merged. all done. can you close please.

**Comment by dmarkov** [comment]
> @dmarkov What should I do? There's an impediment blocking me. Thanks.

@jrdalpra if you removed the puzzle, I will close the ticket right after the next deployment cycle

**Comment by dmarkov** [comment]
> @dmarkov it was merged. all done. can you close please.

@jrdalpra thank you

**Comment by jrdalpra** [comment]
@dmarkov there's no puzzle anymore. can you close? thanks.

**Comment by jrdalpra** [comment]
@dmarkov there's no puzzle anymore. can you close? thanks.

**Comment by dmarkov** [comment]
> @dmarkov there's no puzzle anymore. can you close? thanks.

@jrdalpra will do, right after the next successful deployment cycle

**Comment by dmarkov** [comment]
@yegor256 the code made here contains a puzzle `20-b02d0160`/#32, which will be resolved soon

**Comment by dmarkov** [comment]
@yegor256 Thanks all, closed

**Comment by dmarkov** [comment]
@jrdalpra thanks, paid, **30 mins** to your account, payment ID is `AP-20S716719H473854C`, task took 141 hours and 46 mins to complete. added +30 to your rating, now it is equal to [+248](http://www.netbout.com/b/36044?open=rating)

**Comment by jrdalpra** [comment]
@dmarkov  @yegor256 thanks

2016-01-14 7:53 GMT-02:00 Dan Markov <notifications@github.com>:

> @jrdalpra <https://github.com/jrdalpra> thanks, paid, *30 mins* to your
> account, payment ID is AP-20S716719H473854C, task took 141 hours and 46
> mins to complete. added +30 to your rating, now it is equal to +248
> <http://www.netbout.com/b/36044?open=rating>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jcabi/jcabi-w3c/issues/20#issuecomment-171590998>.
>



-- 
José Volmei Dal Prá Junior - (49) 9112 9359
Bacharel em Ciência da Computação - UnoChapecó
Pós-Graduado em Desenvolvimento de Software Com Java - Unoesc Xxe
Consultor Java e TotalCross
https://github.com/jrdalpra
http://www.kombo.com.br/meucurriculo/jrdalpra
http://www.linkedin.com/in/jrdalpra
msn: jr_dalpra@hotmail.com
skype: jrdalpra
e-mail: jrdalpra@gmail.com

**Comment by dmarkov** [comment]
> @dmarkov  @yegor256 thanks
> 
> 2016-01-14 7:53 GMT-02:00 Dan Markov <notifications@github.com>:
> 
> > @jrdalpra <https://github.com/jrdalpra> thanks, paid, *30 mins* to your
> > account, payment ID is AP-20S716719H473854C, task took 141 hours and 46
> > mins to complete. added +30 to your rating, now it is equal to +248
> > <http://www.netbout.com/b/36044?open=rating>
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/jcabi/jcabi-w3c/issues/20#issuecomment-171590998>.
> >
> 
> 
> 
> -- 
> José Volmei Dal Prá Junior - (49) 9112 9359
> Bacharel em Ciência da Computação - UnoChapecó
> Pós-Graduado em Desenvolvimento de Software Com Java - Unoesc Xxe
> Consultor Java e TotalCross
> https://github.com/jrdalpra
> http://www.kombo.com.br/meucurriculo/jrdalpra
> http://www.linkedin.com/in/jrdalpra
> msn: jr_dalpra@hotmail.com
> skype: jrdalpra
> e-mail: jrdalpra@gmail.com
> 

@jrdalpra np

**Comment by dmarkov** [comment]
@yegor256 last puzzled solved `20-b02d0160`/#32

**Comment by 0pdd** [comment]
@dmarkov all puzzles are solved
