### ISSUE TITLE
DefaultValidationResponse is not an immutable implementation

### ISSUE THREAD

**Issue by simonjenga** [jcabi/jcabi-w3c#25]
Implementations of the interface ```com.jcabi.w3c.ValidationResponse``` MUST be immutable and thread-safe!

The class ```com.jcabi.w3c.DefaultValidationResponse``` implements that interface; however, it is not immutable since it has an evil ```setter``` method. 

```
/**
 * Set validity flag.
 * @param flag The flag to set
 */
public void setValid(final boolean flag) {
	this.ivalid = flag;
}
```

This method is also ```unused``` throughout the whole project. Why was it added?

**Comment by dmarkov** [comment]
@yegor256 dispatch this issue please, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by yegor256** [comment]
@simonjenga looks like a bug to me, thanks

**Comment by dmarkov** [comment]
@simonjenga thanks for the report, I topped your acc for 15 mins, payment ID `72448739`

**Comment by dmarkov** [comment]
@piddubnyi this ticket is yours now, please proceed, and keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Any technical questions you should ask right here... The cost of this task is **30 mins** (this is exactly how much will be paid, not less not more), when the task is [done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by piddubnyi** [comment]
@simonjenga The fix is merged now. Please close the issue.

**Comment by simonjenga** [comment]
@piddubnyi Not yet. This class is NOT thread safe as the documentation states.

If multiple threads access the mutator methods ```com.jcabi.w3c.DefaultValidationResponse.addError(Defect)``` and ```com.jcabi.w3c.DefaultValidationResponse.addWarning(Defect)``` , there will be ConcurrentModifications of the ```java.util.HashSet<Defect>```. This set must be ```synchronized``` externally to prevent that from happening.

Also make a change on the interface class documentation to be: ```Implementation may be mutable BUT thread-safe.```

**Comment by simonjenga** [comment]
@piddubnyi An explicit lock on the mutator method is needed:
```
synchronized (this.hashset) {
    this.hashset.add(error);
} 
```

**Comment by piddubnyi** [comment]
@simonjenga Merged now with thread-safe set wrappers.

**Comment by simonjenga** [comment]
@piddubnyi An explicit lock on the mutator method is needed:
```
synchronized (this.hashset) { 
    this.hashset.add(error); 
}
````
Also, if you take a look at: ```#asText(final Set<Defect> defects)``` you will notice that it uses a ```StringBuilder``` which is not thread safe.

Please take your time.

**Comment by piddubnyi** [comment]
@simonjenga merged now. Let's close this, since CopyOnWriteArraySet provide enough thread safety.

**Comment by simonjenga** [comment]
@piddubnyi It looks like contradiction. Let me close it so we all move on.

**Comment by simonjenga** [comment]
I am closing this issue though contradictory. I wouldn't want to get in the way and withhold any Transaction ID to anyone. It would be mean to do so. New issue related to this one may be submitted.

**Comment by simonjenga** [comment]
I am closing this issue though contradictory. I wouldn't want to get in the way and withhold any Transaction ID to anyone. It would be mean to do so. A new issue related to this one may be submitted.

**Comment by dmarkov** [comment]
@piddubnyi **30 mins** was added to your account, many thanks for your contribution (payment 74520415)! The task took 290 hours and 2 mins.

+30 to your rating, your total score is [-15](http://www.netbout.com/b/35966?open=rating)
