### ISSUE TITLE
DefaultCssValidator.java:71-73: introduce a test case to...

### ISSUE THREAD

**Issue by dmarkov** [jcabi/jcabi-w3c#32]
Puzzle `20-b02d0160` in `src/main/java/com/jcabi/w3c/DefaultCssValidator.java:71-73` has to be resolved: introduce a test case to test the success path when has the pattern below and another one to test the processed path at this method... The puzzle was created by jrdalpra on 8-Jan-2016.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by dmarkov** [comment]
@piddubnyi please go ahead with this task, it's yours

**Comment by piddubnyi** [comment]
@dmarkov Task is fixed and merged in #33. Please close.

**Comment by dmarkov** [comment]
> @dmarkov Task is fixed and merged in #33. Please close.

@piddubnyi thanks

**Comment by dmarkov** [comment]
@yegor256 Thanks all, closed

**Comment by dmarkov** [comment]
@piddubnyi Thank you, I have added **30 mins** to your account in payment/transaction "`75839782`", time consumed: 191 hours and 19 mins

+30 added to your rating, at the moment it is: [+150](http://www.netbout.com/b/35966?open=rating)
