### ISSUE TITLE
Deprecated w3c validator:  "This interface to HTML5 document checking is obsolete. Use an interface to https://validator.w3.org/nu/ instead."

### ISSUE THREAD

**Issue by amihaiemil** [jcabi/jcabi-w3c#35]
You get the warning above when using ``new ValidatorBuilder()`` . According to the first comment of ``sideshowbarker`` from the following thread:

http://stackoverflow.com/questions/30716156/this-interface-to-html5-document-checking-is-deprecated

we should switch to the new validator: https://validator.w3.org/nu/ and stop using the deprecated one: http://validator.w3.org/

**Comment by dmarkov** [comment]
@yegor256 please do something about this issue

**Comment by dmarkov** [comment]
@amihaiemil thanks for the report, I topped your acc for 15 mins, payment ID `AP-8BW5767508554061P`

**Comment by dmarkov** [comment]
@nikoladespotoski please help, the task is yours

**Comment by NikolaDespotoski** [comment]
@dmarkov assign to someone else.

**Comment by dmarkov** [comment]
> @dmarkov assign to someone else.

@nikoladespotoski all right, we'll find someone else for this task

**Comment by dmarkov** [comment]
@nesterov-n can you please help? Keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If you have any technical questions, don't hesitate to ask right here; Budget here is **30 mins** (keep [this principle](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind)

**Comment by nesterov-n** [comment]
@dmarkov Please, assign someone else

**Comment by dmarkov** [comment]
> @dmarkov Please, assign someone else

@nesterov-n deducted 30 from your rating :(

**Comment by dmarkov** [comment]
> @dmarkov Please, assign someone else

@nesterov-n no problem, I will try to find somebody else

**Comment by dmarkov** [comment]
@prondzyn could you please pick this up? This [article](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) explains how we work. Any technical questions you may ask right here

This task's budget is **30 mins**. This is exactly how much will be paid when the problem explained above is solved. See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by prondzyn** [comment]
@dmarkov I created PR #36 for this.

**Comment by dmarkov** [comment]
> @dmarkov I created PR #36 for this.

@prondzyn thanks

**Comment by prondzyn** [comment]
@dmarkov please give me more time. PR is still on code review but I will finish the task.

**Comment by dmarkov** [comment]
> @dmarkov please give me more time. PR is still on code review but I will finish the task.

@prondzyn sure, take your time

**Comment by prondzyn** [comment]
@amihaiemil please close the task. It is finished.

**Comment by dmarkov** [comment]
@prondzyn Thanks so much! Your account was topped up for **30 mins** (transaction ID is `AP-4J023649S4419182J`, the task took 384 hours and 11 mins). added +30 to your rating, now it is equal to [+30](http://www.netbout.com/b/35715?open=rating)
