### ISSUE TITLE
Google Group link is broken

### ISSUE THREAD

**Issue by dialex** [jcabi/jcabi-w3c#37]
The link to your Google Group is broken as you can see
![screen shot 2016-09-13 at 14 44 58](https://cloud.githubusercontent.com/assets/2140450/18476105/b5d4579c-79c0-11e6-980e-d8e0f05d9bbc.png)

Why don't you use this GitHub for discussion?

**Comment by dmarkov** [comment]
@yegor256 please pay attention to this issue ([par.21](http://at.teamed.io/policy.html#21))

**Comment by yegor256** [comment]
@rultor release, tag is `1.3`

**Comment by yegor256** [comment]
@dialex it's fixed, in version 1.3 we don't have newsgroups any more. Thanks!
