### ISSUE TITLE
Obsolete?

### ISSUE THREAD

**Issue by cdalexndr** [jcabi/jcabi-w3c#47]
Last version is from 2016.

Running it returns invalid error fields: 

- column and line are always zero, but the html has newlines
- `isource` incomplete. Example: `er-->`
- `iexplanation` and `msg` are always empty
- `imessage` is incomplete. Example: `The`

Configuration:
```
        testImplementation group: 'com.jcabi', name: 'jcabi-w3c', version: '1.3'
        testImplementation group: 'com.jcabi', name: 'jcabi-matchers', version: '1.5.3'
```

**Comment by yegor256** [comment]
@cdalexndr try version 1.4.0, just released
