### ISSUE TITLE
default html validator url uses http protocol, but only https is served and "moved permamently" response not handled correctly.

### ISSUE THREAD

**Issue by mkleint** [jcabi/jcabi-w3c#48]
https://github.com/jcabi/jcabi-w3c/blob/master/src/main/java/com/jcabi/w3c/ValidatorBuilder.java#L74
uses http protocol but that is no longer served by validator.w3.org only https is.

the resulting "moved permanently" response is not handled by the library and an exception is thrown.

workaround is to explicitly create an html validator with https protocol

**Comment by mkleint** [comment]
affects 1.3 version of the library

**Comment by yegor256** [comment]
@mkleint fixed, try version `1.4.0` (just released)
