### ISSUE TITLE
Copyright section is outdated

### ISSUE THREAD

**Issue by maurezen** [jcabi/jcabi-w3c#5]
Copyright sections still feature 2014 as a year.

**Comment by dmarkov** [comment]
I'll find a developer for the task soon...

**Comment by dmarkov** [comment]
@romankisilenko it's yours now, please proceed keeping in mind [our principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Feel free to ask any technical questions right here in the ticket

This task's budget is **30 mins**. This is exactly how much will be paid when the problem explained above is solved. See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by dmarkov** [comment]
@maurezen thanks for reporting! I topped your account for 15 mins, transaction 50258055

**Comment by RomanKisilenko** [comment]
@maurezen PR was reviewed and closed, please close this issue.

**Comment by dmarkov** [comment]
@romankisilenko thanks, I just added **30 mins** to your account, payment `50616262`... +30 to your rating, your total score is +330
